luci-app-rclone: fix on CIDR format ipaddr
ElonH/Rclone-OpenWrt pull request #22
Opened 2022-08-04 10:03 UTC by jjm2473

2022-08-05 14:20 UTC, 1715173329 requested changes
this repo is read only, any new changes should be done in [immortalwrt/luci](https://github.com/immortalwrt/luci).

2022-08-05 14:20 UTC, 1715173329 commented on luci-app-rclone/root/usr/share/rpcd/acl.d/luci-app-rclone.json
> -{
js luci need it to work.

2022-08-05 14:20 UTC, 1715173329 commented on luci-app-rclone/root/etc/uci-defaults/100_luci-rclone
> -#!/bin/sh
uh? why delete this?

2022-08-05 14:20 UTC, 1715173329 commented on luci-app-rclone/Makefile
> +PKG_RELEASE:=
what?

2022-08-05 14:20 UTC, 1715173329 commented on luci-app-rclone/luasrc/model/cbi/rclone.lua
> +if type(trip) == 'table' then
better solution is using something like `window.location.hostname`, rather than introducing more hacks.

2022-08-11 06:12 UTC, jjm2473 commented on luci-app-rclone/root/usr/share/rpcd/acl.d/luci-app-rclone.json
> -{
这个删错了

2022-08-11 06:13 UTC, jjm2473 commented on luci-app-rclone/root/etc/uci-defaults/100_luci-rclone
> -#!/bin/sh
config和init在openwrt提供的rclone里面都有了，文件重复会导致opkg安装失败

2022-08-11 06:14 UTC, jjm2473 commented on luci-app-rclone/Makefile
> +PKG_RELEASE:=
为了兼容luci 21和老的luci。
luci 21的构建脚本是不关心RELEASE字段的，所以直接合并到VERSION字段就行了，这样可以兼容不同版本的luci

2022-08-11 06:16 UTC, jjm2473 commented on luci-app-rclone/luasrc/model/cbi/rclone.lua
> +if type(trip) == 'table' then
哦，但是界面上本来也不是链接，只是提示webui应该填什么后端地址。这里只是修复bug，逻辑跟以前一样

2022-08-11 06:38 UTC, jjm2473 commented
提交到这里去了 https://github.com/immortalwrt/luci/pull/204

2022-08-11 06:38 UTC, closed without merging